image: alpine/latest
packages:
  - git
  - openssh
secrets:
  - 0639564d-6995-4e2e-844b-2f8feb0b7fb1
environment:
  repo: zmk-config
  github: git@github.com:ficcdaf
tasks:
  - mirror: |
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      cd "zmk"
      git remote add github "$github/$repo.git"
      git push --mirror github
